env:
 language: ruby
cache: bundler
language: ruby
rvm:
  - 2.5
  - 2.6
  - jruby
  - truffleruby
  matrix:
  - secure: encrypted string
  global:
  - secure: qvE+vv6rYnmvnicrBsrSVfIq3OZ/mqXd85HzQ5fwtBgjZCIUU7tH84eihhXZItW9ahsBTHBq+HUCSWRz3hNCCgdYyuEMpdDDyxAvmpLqucC3ZEjAwT25KidY0kOThcD6DDvCvd5Jcx4b4/v4uN98Jy+T7Vie14SsGOIxZGNKCIzJbErg/7NnJFKz7tGvoFPLr1hA8wR80Z4OE5SpebRligagcT4v9N0j7v5KXJPW6G2Lef9y9JkuJGL+l2N+3KHloIr0YTDcWZtmS0R19Uf4DOt/6IGl3XyYXbSyN15YDwT/W2TncRgTCPVGRXoRJuVN+ZRSPlZ62PAYKQ2cQWvPUVeogMBJboxog/UPj6dp5E91JdliDGzYXeh0gOVmBspEz1Z+jLYuQ3M+8je3qmRhloQbKovEE92ooj9gIN42FZx3fHBIjXVQ92ODZwAM9MGGQ+1alW9AduY2W8zEpAD996YIKwU7WrKH3vwbukOGuG0vuULGZzNr56XbGEFBUlSu/8AQnMisUuGyhJvgpHM4AGH1deMTsaT1SMjSlZk5E1ryGsUHq28tQ2BAJeWf/VftylyYZE3Pvb07te9tFjkLiyqhFt+NtXT6z7jYf9IZvdteNeOPxqFLn/x0bQiqEwP2VWEx34p/9dTHdiBeuDz5RdM4LDzDwQQfNBC+TqPzi3k=
  - secure: hjK61ScyRhVaY9a/vILOimghccSBqfI461AM59yRC1Ix4xkLeCnoDFoX/371kY/+s+4pYakZ08+YY/7FPOyzep00dI7Wn0GSfLZay5YWRmzV7HXMaDkM62MEUqsxBwKC47HWl8HWpD+XS2ZlWrGQZJTnl/scciphIlZ8unNEja8TaMXfKxIGQBhfi8E8tgbUDtPhLoxodZuwEuLRyrU/S63JrtrNUmho4JJlf4J9WGR1ngqlT3+XYHa++iSJzkGtbqfp78si0FEgkLNlCgpbBQVCJelHnHhYtXpKljl/E5LAot77qzHBagoQ+kM4jRg9+IaxjSPPJeXrp8YQBNWkh+tue6zLagIAViDrf7at3+/e3sTvsjJpbXe9GQpsuIWLvvtDmLDfR090vZ7sqxkRAWZ8Czswe6QW92+vs/uRnm37jrKH8n4cmIQzpQPU2EV0P8wtlwvD4OfhlF/EltVUJ+ZwLa0/VuHNbVUF37aNX1U7DYSRw8YswTu2etYzlA0w+29oGkayl1a5A2d9a7FImgfyMyGnGcBXQqHTXMmqPInfJseZZ7XYcheSGiWb6NqLc3/eanGe2t4LInPf7fG1uboM1BAwYg4NbWXi0vBQKIAj+W0/RhLBWgUEnsj3j37WoBj+3lR06AMx+Dg6WrutuKQ21JEOnccr2v1znjePhos=
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
    
